FROM node:20-bullseye

# Instalar Nest CLI globalmente
RUN npm install -g @nestjs/cli

WORKDIR /usr/src/app

# Copiar package files e instalar dependencias
COPY package*.json ./
RUN npm install

# El código se monta como volumen, no se copia
CMD ["npm", "run", "start:dev"]